# SPDX-FileCopyrightText: 2025 Daniele Paletti <danielepaletti98@gmail.com>
#
# SPDX-License-Identifier: CC-BY-SA-4.0

ci:
  # reuse is in another ci job
  skip: [reuse]

repos:
  - repo: local
    hooks:
      - id: md_lint_format
        name: md_lint_format
        description: run formatting and linting on markdown files
        entry: mise run md_lint_format
        language: system
        pass_filenames: false

      - id: dco_enforce
        name: dco_enforce
        description: add dco signature on commit
        entry: mise run dco_enforce
        language: system
        stages: [prepare-commit-msg]
        always_run: true
        pass_filenames: false

  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse
