[env]
# Remove time from commits, keep only date
_.source = "./.config/computed_env_vars.sh"
GIT_COMMITTER_DATE="{{env.UTC_DAY_BEGIN}}"
GIT_AUTHOR_DATE="{{env.UTC_DAY_BEGIN}}"

VALE_CONFIG_PATH = "{{config_root}}/.config/vale/vale.ini"

[tools]
node = "24"
python = "3.13"
pandoc = "3.6.1"

# Prose linting
vale = "3.12.0"

# Precommit hooks
"pipx:pre-commit" = "latest"

# Markdown utilities
## linting
"npm:markdownlint-cli2" = "0.18.1"
## previewing
"pipx:grip" = "latest"


# Formatting
"npm:prettier" = "3.6.2"


# Diagrams
"npm:@mermaid-js/mermaid-cli" = "11.6.0"

[tasks.setup]
description = "Setup development environment"
run = """
echo "Setting up development tools..."
mise install
pre-commit install
vale sync
echo "Development environment ready!"
"""

[tasks.md_lint]
description = "Run linting on all markdown files."
run = """
echo "Running markdown linting"
vale '**/*.md'
markdownlint-cli2 '**/*.md'
"""

[tasks.precommit]
description = "Run precommit hooks"
run = """
echo "Running pre-commit on all files..."
pre-commit run --all-files
"""
