%% SPDX-FileCopyrightText: 2025 <github.com/dpaletti/orti> contributors
%% SPDX-License-Identifier: CERN-OHL-S-2.0

graph TD
BATTERY["2 x AAA BATTERY"]
USB-C
VOLTAGE-REGULATOR["TPS76301DBVR <br> VOLTAGE REGULATOR"]
MICROCONTROLLER["NRF-52840 <br> MICROCONTROLLER"]
TEMPERATURE["STS4 <br> TEMPERATURE SENSOR"]

subgraph OSCILLATOR
         STAGE_1["DIFFERENTIAL AMPLIFIER (1)"]
         STAGE_2["DIFFERENTIAL AMPLIFIER (2)"]
         STAGE_3["DIFFERENTIAL AMPLIFIER (3)"]

         STAGE_1 --> STAGE_2
         STAGE_2 --> STAGE_3
         STAGE_3 --> STAGE_1
end

subgraph HUMIDITY["SOIL PERMITTIVITY"]
         LINE["TRANSMISSION LINE (inside the soil)"]
         MEASURED_FREQUENCY["BASELINE FREQUENCY INFLUENCED BY SOIL PERMITTIVITY"]
         OSCILLATOR --> |drives| LINE
         LINE --> |produces| MEASURED_FREQUENCY
         LINE --> |feedbacks| OSCILLATOR
         MEASURED_FREQUENCY --> DIVIDER["FREQUENCY DIVIDER"]
end

USB-C --> |feeds| VOLTAGE-REGULATOR
VOLTAGE-REGULATOR --> |recharges| BATTERY
BATTERY -->|powers| MICROCONTROLLER
BATTERY -->|powers| HUMIDITY
BATTERY -->|powers| TEMPERATURE

TEMPERATURE -->|signals| MICROCONTROLLER
HUMIDITY -->|signals| MICROCONTROLLER
