name: Validate Mermaid Diagrams

on:
  pull_request:
    branches: [main]
    paths:
      - "**.mmd"
      - "**/resources/*.mmd.png"
  push:
    branches: [main]
    paths:
      - "**.mmd"
      - "**/resources/*.mmd.png"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Run mise setup
        run: mise run setup

      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Find all .mmd files
        id: find-files
        run: |
          echo "files=$(find . -name '*.mmd' -type f | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Compile all diagrams
        run: mise run compile_mermaid ${{ steps.find-files.outputs.files }}

      - name: Check for uncommitted changes
        run: |
          if ! git diff --quiet; then
            echo "::error::Mermaid diagrams are out of sync!"
            echo "Please run the pre-commit hook locally to generate PNG files:"
            echo "  git add *.mmd"
            echo "  git commit"
            echo ""
            echo "Changed files:"
            git diff --name-only
            exit 1
          fi

          echo "All Mermaid diagrams are up-to-date!"
