name: REUSE Compliance Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  reuse-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5
